EARLY_DUNGEONS = {
	"Beach Cave (4F)",
	"Drenched Bluff (6F)",
	"Mt. Bristle (9F)",
	"Waterfall Cave (8F)",
	"Apple Woods (12F)",
	"Craggy Coast (9F)",
	"Side Path (5F)",
	"Mt. Horn (14F)",
	"Rock Path (5F)",
	"Foggy Forest (11F)",
	"Forest Path (5F)",
	"Steam Cave (8F)",
	"Amp Plains (10F)",
	"Northern Desert (15F)",
	"Quicksand Cave (10F)",
	"Crystal Cave (11F)",
	"Crystal Crossing (13F)",
	"Chasm Cave (8F)",
	"Dark Hill (15F)",
	"Sealed Ruin (8F)",
	"Dusk Forest (8F)",
	"Deep Dusk Forest (12F)",
	"Treeshroud Forest (20F)",
	"Brine Cave (9F)",
	"Hidden Land (15F)",
	"Temporal Tower (13F)",
	"Serenity River (8F)",
	"Landslide Cave (13F)",
	"Lush Prarie (6F)",
	"Tiny Meadow (5F)",
	"Labyrinth Cave (10F)",
	"Oran Forest (5F)"	
}

LATE_DUNGEONS = {
	"Mystifying Forest (13F)",
	"Blizzard Island (20F)",
	"Crevice Cave (10F)",
	"Surrounded Sea (19F)",
	"Miracle Sea (18F)",
	"Mt. Travail (19F)",
	"The Nightmare (17F)",
	"Spacial Rift (15F)",
	"Concealed Ruins (29F)",
	"Marine Resort (18F)",
	"Bottomless Sea (49F)",
	"Shimmer Desert (9F)",
	"Mt. Avalanche (19F)",
	"Giant Volcano (19F)",
	"World Abyss (29F)",
	"Sky Stairway (49F)",
	"Mystery Jungle (29F)",
	"Lake Afar (25F)",
	"Happy Outlook (20F)",
	"Mt. Mistral (20F)",
	"Shimmer Hill (18F)",
	"Lost Wilderness (18F)",
	"Midnight Forest (25F)",
	"Star Cave (15F)"
}

SKY_PEAK_DUNGEONS = {
	"1st Station ",
	"2nd Station ",
	"3rd Station ",
	"4th Station ",
	"5th Station ",
	"6th Station ",
	"7th Station ",
	"8th Station ",
	"9th Station ",
	"Sky Peak Summit "
}

