EARLY_DUNGEONS = {
	"Beach Cave",
	"Drenched Bluff",
	"Mt. Bristle",
	"Waterfall Cave",
	"Apple Woods",
	"Side Path",
	"Craggy Coast",
	"Rock Path",
	"Mt. Horn",
	"Forest Path",
	"Foggy Forest",
	"Steam Cave",
	"Amp Plains",
	"Northern Desert",
	"Quicksand Cave",
	"Crystal Cave",
	"Crystal Crossing",
	"Chasm Cave",
	"Dark Hill",
	"Sealed Ruin",
	"Dusk Forest",
	"Deep Dusk Forest",
	"Treeshroud Forest",
	"Brine Cave",
	"Hidden Land",
	"Temporal Tower",
	"Oran Forest",
    "Tiny Meadow",
    "Lush Prairie",
    "Serenity River",
    "Landslide Cave",
    "Labyrinth Cave"
}

LATE_DUNGEONS = {
	"Mystifying Forest",
	"Blizzard Island",
    "Crevice Cave",
    "Surrounded Sea",
    "Miracle Sea",
    "Aegis Cave",
    "Mt. Travail",
    "The Nightmare",
    "Spacial Rift",
	"Concealed Ruins",
    "Marine Resort",
    "Lake Afar",
    "Happy Outlook",
    "Mt. Mistral",
    "Shimmer Hill",
    "Lost Wilderness",
    "Midnight Forest",
    "Star Cave",
	"Bottomless Sea",
    "Shimmer Desert",
    "Mt. Avalanche",
    "Giant Volcano",
    "World Abyss",
    "Sky Stairway",
    "Mystery Jungle"
}

SKY_PEAK_DUNGEONS = {
	"1st Station ",
	"2nd Station ",
	"3rd Station ",
	"4th Station ",
	"5th Station ",
	"6th Station ",
	"7th Station ",
	"8th Station ",
	"9th Station ",
	"Sky Peak Summit "
}